version: '3.9'

services:
  redis:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'
        reservations:
          cpus: '0.25'
          memory: '128M'
    image: redis:7.4
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning