openapi: 3.0.1
info:
  title: URL Shortening API
  version: 1.0.0
  description: An API to shorten URLs with expiration date support.
servers:
  - url: http://localhost:8080
    description: Development Server
paths:
  /v1/shorten:
    post:
      summary: Shorten a URL
      description: Accepts a URL and returns a shortened version.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: The URL that you want to shorten.
                  example: "https://example.com"
                expiration:
                  type: string
                  format: date-time
                  description: The expiration date of the shortened URL in ISO format (yyyy-MM-dd'T'HH:mm:ss).
                  example: "2024-10-07T12:00:00"
      responses:
        '200':
          description: Successfully shortened URL.
          content:
            application/json:
              schema:
                type: string
                example: "http://localhost:8080/shortened_link_id"
        '400':
          description: Invalid request body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Wrong request body."

  /{link}:
    get:
      summary: Retrieve the original URL
      description: Given a shortened URL link, retrieve the original URL.
      parameters:
        - name: link
          in: path
          required: true
          description: The shortened link identifier.
          schema:
            type: string
      responses:
        '302':
          description: Redirects to the original URL.
        '400':
          description: Invalid link provided.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Empty link provided."
